### PR TITLE
Added read/unread functionality

### PR DESCRIPTION
**Pull request by dbwest**
on the forum show, users can see how many new posts they haven't read

notes:
-after this change, when a user posts a comment it is counted as unread. this needs fixed
-no tests were written yet

### CODE REVIEW

**Comment by mdarby** [comment]
Cool -- a few things:
- You need to rebase or merge the current master first
- Please remove the /doc folder (unless there is good reason to keep it)
- We need tests :)

**Comment by dbwest** [comment]
Thanks for the quick reply. done the first two. just need tests now. I'll write some rspec

**Comment by mdarby** [comment]
Awesome, and thanks :)

**Comment by dbwest** [comment]
Hey, I don't know how to write the tests now. I still want to share what I have and keep it current with the code base. Let me know if there's something I can do, like make a branch. In the meantime, I'll wait until I can figure out how to do the testing or learn from someone about it.

**Comment by mdarby** [comment]
All good -- are your updates on a branch somewhere I can look at?

**Comment by dbwest** [comment]
https://github.com/dbwest/conclave/tree/read-unread

**Comment by mdarby** [comment]
Could you rebase off of master and resend a pull request? I'll merge and backfill with tests.

**Pull request closed without merging**
