### PR TITLE
Conversation refactor

### PR DESCRIPTION
**Pull request by skord**
Thought I'd get some eyes on this before I merge. 

File attachments aren't going to work unless the comments are created differently in the controllers, currently the attributes are assigned one at a time. 

This set of commits implicitly sets up the relationships doing away with explicit behavior. However, because it uses nested attributes, the current specs and validations don't work (the associated model instance doesn't exist yet). 

So one or the other I guess.

### CODE REVIEW

**Comment by skord** [comment]
ugh, FF problems. sorry.

**Comment by mdarby** [comment]
Looks like we collided on the feature...

**Comment by skord** [comment]
Yeah, I'm going to have to cherrypick those three commits into skord/master

**Comment by mdarby** [comment]
Sorry man, I didn't know you were working on it.

**Comment by skord** [comment]
No, it's my fault for pushing a bad rebase.

**Comment by skord** [comment]
Oh, no I didn't, we actually collided. Happens.

**Pull request closed without merging**
