### PR TITLE
User has_many :conversations and vice-versa

### PR DESCRIPTION
**Pull request by mikegee**
Model associations for issue #6.

I haven't looked at the UI yet to see where we should put a listing of "My Conversations".

### CODE REVIEW

**Comment by skord** [comment]
Does there really need to be a 1:N mapping for Users:Conversations? Has many conversations through comments?

**Comment by mdarby** [comment]
But then we have to scope that to where the comment is the first in the conversation. Sounds expensive; especially when we're just trying to enumerate records...

**Comment by DVG** [comment]
It seems like the intent of this test has changed. The it doesn't match up with the new implementation, which is that it's creator is a User (good test) but we've also removed the check that the creator is correct (also a good test). I'd suggest splitting this back into 2 tests.

```
   it "should know about its original author" do
-    u1 = create(:user)     
-    u2 = create(:user)     
-    c1 = create(:comment, :user => u1)     
-    c2 = create(:comment, :user => u2)     
-    @conversation.comments << c1   
-    @conversation.comments << c2   
-   
-    @conversation.original_author.should == u1
+    @conversation.original_author.should be_a(User)
   end
```

**Comment by skord** [comment]
@mdarby Thinking as an end user here, for what reason would there be to know a conversation you've started and one you've been a part of? They're all conversations you've been a part of.

**Comment by mdarby** [comment]
Just my $0.02, but I'd dig a feature that would allow me to quickly find what Conversations I've started, as those mean a bit more to me (as I started them). I usually go to a Forum and look for updates on stuff I've created/started.

**Comment by skord** [comment]
But there's some sort of namespace clash here. I'd expect that:

user.conversations would return all the conversations I'm a part of and a scope with a proc would be more appropriate for something like user.conversations.authored to get the conversations you're in charge of.

**Comment by mdarby** [comment]
Either way would work, but yeah, I would rename `user.conversations` to something like `user.authored_conversations`. Either way.

**Comment by mikegee** [comment]
I considered naming that association "conversations_started". It's easy to change, if we want to do that.

**Pull request merged**
